Update copy-artifact.yaml

diff --git a/.github/workflows/copy-artifact.yaml b/.github/workflows/copy-artifact.yaml
--- a/.github/workflows/copy-artifact.yaml
+++ b/.github/workflows/copy-artifact.yaml
@@ -67,4 +67,4 @@ jobs:
         run: bash ./scai-demo/copy-artifact/copy-artifact.sh
       - name: Display attestation file
         run: |
-          echo ./scai-demo/copy-artifact/copy-artifact-metadata/copied-artifact.scai.json
+          cat ./scai-demo/copy-artifact/copy-artifact-metadata/copied-artifact.scai.json || echo "file not found"
